version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    user: postgres # importante definir o usuário
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres # senha padrão
      - POSTGRES_USER=postgres # usuário padrão
      - POSTGRES_DB=db # necessário porque foi configurado assim no settings
    ports:
      - 5430:5432 # repare na porta externa 5430
    networks:
      - skynet

  pgadmin:
    image: dpage/pgadmin4:6
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 5052:80
    networks:
      - skynet

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 8080
      - 80
    ports:
      - "8000:8000"
      - "8080:80"
    volumes:
      - .env:/app/.env
    depends_on:
      - db
    networks:
      - skynet

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    logging:
      driver: "none"
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - skynet

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - skynet

volumes:
  pgdata:
  pgadmin:

networks:
  skynet:
